title: Curiosità matematiche
description: Piccole curiosità dal mondo della matematica
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme
navbar-links:
  Home: ""
  Articoli: "posts"
  Chi sono: "about"
